theme: jekyll-theme-minimal
title: Stihia | Security for AI Agents
description: Stihia is a European Union based company that provides products and services in the field of AI security. Some of them include - prompt injection prevention, red teaming and penetration testing, corporate trainings, and more.
